[remap]
KEY_F1 = ["KEY_MUTE"]
KEY_F2 = ["KEY_VOLUMEDOWN"]
KEY_F3 = ["KEY_VOLUMEUP"]
KEY_F4 = ["KEY_MICMUTE"]
KEY_F5 = ["KEY_BRIGHTNESSDOWN"]
KEY_F6 = ["KEY_BRIGHTNESSUP"]

KEY_F8 = ["KEY_RESERVED"]
KEY_F9 = ["KEY_RESERVED"]
KEY_F10 = ["KEY_RESERVED"]

# copilot key 
KEY_F23 = ["KEY_SEARCH"]


[settings]
GRAB_DEVICE = "true"
